"""Initial migration

Revision ID: d376f7266e08
Revises: 
Create Date: 2024-11-17 12:13:02.474935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd376f7266e08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_schedule', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('guests_comfort', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('romantic_focus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('music_enjoyment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('packing_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tv_importance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('study_social', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('commitments_sleep', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('travel_offcampus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('roommate_bedtime', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('binge_tv', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('similar_major_importance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiet_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alarm_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('smoke_drink', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('appliances_usage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('guests_frequency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('room_decoration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('roommate_closeness', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('family_visits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('laundry_frequency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activity_priorities', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('social_events', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bedtime_weekdays', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('noise_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('room_absence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ideal_temperature', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('windows_open', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sleep_flexibility', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('guest_curfew', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('neighbors_importance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('eat_room', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('conflict_handling', sa.Integer(), nullable=True))
        batch_op.drop_column('question1')
        batch_op.drop_column('question3')
        batch_op.drop_column('question2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question2', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('question3', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('question1', sa.INTEGER(), nullable=False))
        batch_op.drop_column('conflict_handling')
        batch_op.drop_column('eat_room')
        batch_op.drop_column('neighbors_importance')
        batch_op.drop_column('guest_curfew')
        batch_op.drop_column('sleep_flexibility')
        batch_op.drop_column('windows_open')
        batch_op.drop_column('ideal_temperature')
        batch_op.drop_column('room_absence')
        batch_op.drop_column('noise_level')
        batch_op.drop_column('bedtime_weekdays')
        batch_op.drop_column('social_events')
        batch_op.drop_column('activity_priorities')
        batch_op.drop_column('laundry_frequency')
        batch_op.drop_column('family_visits')
        batch_op.drop_column('roommate_closeness')
        batch_op.drop_column('room_decoration')
        batch_op.drop_column('guests_frequency')
        batch_op.drop_column('appliances_usage')
        batch_op.drop_column('smoke_drink')
        batch_op.drop_column('alarm_time')
        batch_op.drop_column('quiet_hours')
        batch_op.drop_column('similar_major_importance')
        batch_op.drop_column('binge_tv')
        batch_op.drop_column('roommate_bedtime')
        batch_op.drop_column('travel_offcampus')
        batch_op.drop_column('commitments_sleep')
        batch_op.drop_column('study_social')
        batch_op.drop_column('tv_importance')
        batch_op.drop_column('packing_amount')
        batch_op.drop_column('music_enjoyment')
        batch_op.drop_column('romantic_focus')
        batch_op.drop_column('guests_comfort')
        batch_op.drop_column('follow_schedule')

    # ### end Alembic commands ###
